### ISSUE TITLE
App crash when SDK gets initialized later

### ISSUE THREAD

**Issue by CsabaMiomni** [snapodds/sdk-android#1]
Implemented to use the latest SDK (2.1.0) however I got a major issue. The app crashes when I try to setup the snapscreen lib.

This is the crash

E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.miomni.Miomni, PID: 18892
    java.lang.NullPointerException: Attempt to invoke virtual method 'boolean com.snapscreen.mobile.SnapscreenTimeService.getCalibrated()' on a null object reference
        at com.snapscreen.mobile.Snapscreen.checkForTokenAndCalibration(Snapscreen.kt:300)
        at com.snapscreen.mobile.Snapscreen.<init>(Snapscreen.kt:43)
        at com.snapscreen.mobile.Snapscreen$Companion.setup(Snapscreen.kt:122)
        at com.miomni.sportsbook.net.WagerThis.prepareSnapscreen(WagerThis.kt:56)
        at com.miomni.sportsbook.ui.activities.HomeActivity.lambda$onCreate$1$com-miomni-sportsbook-ui-activities-HomeActivity(HomeActivity.java:108)
        at com.miomni.sportsbook.ui.activities.HomeActivity$$ExternalSyntheticLambda2.onClick(Unknown Source:2)

Couldn't figure out the issue in the decompiled source code, I can see that the variable 'scope' gets a value later than the method 'checkForTokenAndCalibration()' was called in the constructor, but it gets a value in the onStart method also - dunno where it gets called, I guess from an SDK activity or a fragment. And it looks that the 'timeService' is null at that point, it'll get initiallized in the constructor later.

**Comment by CsabaMiomni** [comment]
I think I found the cause of the issue!

You attach to the application process lifecycle manager to detect if the app was started / stopped. And when you setup the observer, it'll delegate the statuses (CREATED, STARTED, RESUMED, etc, depends on the current status). When onStart() gets called via the observer, you set a variable within the Snapscreen instance. This variable gets checked in the checkForTokenAndCalibration() method as well, and if it's not null, you are going to check the SnapscreenTimeService.getCalibrated(), which is still not initialized at this stage! And the app gets crashed.

You should not observe the application process lifecycle until the Snapscreen object gets fully initialized and ready to use (so addObserver call should be the last line in the constructor, otherwise the half-ready Snapscreen objects 'gets working' out of the blue)
